// Auto-generated by scripts/generate-offline-data.mjs — do not edit
import type { Relationship } from "@ory/client-fetch";

const OFFLINE_EXAMPLES: Record<string, Relationship[]> = {
  "b2b-hierarchy": [
    {
      "namespace": "Business",
      "object": "acme-corp",
      "relation": "admins",
      "subject_set": {
        "namespace": "User",
        "object": "ceo-pat",
        "relation": ""
      }
    },
    {
      "namespace": "Business",
      "object": "acme-corp",
      "relation": "admins",
      "subject_set": {
        "namespace": "User",
        "object": "coo-quinn",
        "relation": ""
      }
    },
    {
      "namespace": "Business",
      "object": "acme-corp",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "auditor-sam",
        "relation": ""
      }
    },
    {
      "namespace": "Business",
      "object": "acme-corp",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "auditor-tina",
        "relation": ""
      }
    },
    {
      "namespace": "Business",
      "object": "globex-inc",
      "relation": "admins",
      "subject_set": {
        "namespace": "User",
        "object": "ceo-rick",
        "relation": ""
      }
    },
    {
      "namespace": "Business",
      "object": "globex-inc",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "auditor-wendy",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "retail",
      "relation": "parent",
      "subject_set": {
        "namespace": "Business",
        "object": "acme-corp",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "wholesale",
      "relation": "parent",
      "subject_set": {
        "namespace": "Business",
        "object": "acme-corp",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "digital",
      "relation": "parent",
      "subject_set": {
        "namespace": "Business",
        "object": "acme-corp",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "insurance",
      "relation": "parent",
      "subject_set": {
        "namespace": "Business",
        "object": "acme-corp",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "globex-saas",
      "relation": "parent",
      "subject_set": {
        "namespace": "Business",
        "object": "globex-inc",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "globex-consulting",
      "relation": "parent",
      "subject_set": {
        "namespace": "Business",
        "object": "globex-inc",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "retail",
      "relation": "managers",
      "subject_set": {
        "namespace": "User",
        "object": "mgr-retail-lisa",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "retail",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "analyst-retail-joe",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "wholesale",
      "relation": "managers",
      "subject_set": {
        "namespace": "User",
        "object": "mgr-wholesale-mike",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "wholesale",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "analyst-wholesale-kate",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "digital",
      "relation": "managers",
      "subject_set": {
        "namespace": "User",
        "object": "mgr-digital-nina",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "digital",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "analyst-digital-paul",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "insurance",
      "relation": "managers",
      "subject_set": {
        "namespace": "User",
        "object": "mgr-insurance-olivia",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "insurance",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "analyst-insurance-ray",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "globex-saas",
      "relation": "managers",
      "subject_set": {
        "namespace": "User",
        "object": "mgr-saas-victor",
        "relation": ""
      }
    },
    {
      "namespace": "LineOfBusiness",
      "object": "globex-consulting",
      "relation": "managers",
      "subject_set": {
        "namespace": "User",
        "object": "mgr-consulting-uma",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-r1",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "retail",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-r2",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "retail",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-r3",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "retail",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-r4",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "retail",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-w1",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "wholesale",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-w2",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "wholesale",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-w3",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "wholesale",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-d1",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "digital",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-d2",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "digital",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-d3",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "digital",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-i1",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "insurance",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-i2",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "insurance",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-gs1",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "globex-saas",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-gs2",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "globex-saas",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-gc1",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "globex-consulting",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-gc2",
      "relation": "parent_lob",
      "subject_set": {
        "namespace": "LineOfBusiness",
        "object": "globex-consulting",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-r1",
      "relation": "account_managers",
      "subject_set": {
        "namespace": "User",
        "object": "am-retail-anna",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-r1",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "rep-retail-dan",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-r2",
      "relation": "account_managers",
      "subject_set": {
        "namespace": "User",
        "object": "am-retail-anna",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-r3",
      "relation": "account_managers",
      "subject_set": {
        "namespace": "User",
        "object": "am-retail-betty",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-r4",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "rep-retail-dan",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-w1",
      "relation": "account_managers",
      "subject_set": {
        "namespace": "User",
        "object": "am-wholesale-ben",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-w2",
      "relation": "account_managers",
      "subject_set": {
        "namespace": "User",
        "object": "am-wholesale-carl",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-w3",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "rep-wholesale-fay",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-d1",
      "relation": "account_managers",
      "subject_set": {
        "namespace": "User",
        "object": "am-digital-elena",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-d2",
      "relation": "account_managers",
      "subject_set": {
        "namespace": "User",
        "object": "am-digital-elena",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-d3",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "rep-digital-george",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-i1",
      "relation": "account_managers",
      "subject_set": {
        "namespace": "User",
        "object": "am-insurance-hank",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-i2",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "rep-insurance-ivy",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-gs1",
      "relation": "account_managers",
      "subject_set": {
        "namespace": "User",
        "object": "am-saas-xander",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-gs2",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "rep-saas-yara",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-gc1",
      "relation": "account_managers",
      "subject_set": {
        "namespace": "User",
        "object": "am-consulting-zach",
        "relation": ""
      }
    },
    {
      "namespace": "Customer",
      "object": "cust-gc2",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "rep-consulting-lily",
        "relation": ""
      }
    }
  ],
  "content-publishing-workflow": [
    {
      "namespace": "Role",
      "object": "writer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "writer-alice",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "writer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "writer-bob",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "writer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "writer-charlie",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "editor",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "editor-diana",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "editor",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "editor-eve",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "publisher",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "publisher-frank",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "publisher",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "publisher-grace",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "reader",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "reader-henry",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "reader",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "reader-irene",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "reader",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "reader-jack",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-draft-1",
      "relation": "author",
      "subject_set": {
        "namespace": "User",
        "object": "writer-alice",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-draft-1",
      "relation": "assigned_editor",
      "subject_set": {
        "namespace": "User",
        "object": "editor-diana",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-draft-1",
      "relation": "draft_editors",
      "subject_set": {
        "namespace": "User",
        "object": "writer-alice",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-draft-2",
      "relation": "author",
      "subject_set": {
        "namespace": "User",
        "object": "writer-bob",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-draft-2",
      "relation": "assigned_editor",
      "subject_set": {
        "namespace": "User",
        "object": "editor-eve",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-draft-2",
      "relation": "draft_editors",
      "subject_set": {
        "namespace": "User",
        "object": "writer-bob",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-draft-3",
      "relation": "author",
      "subject_set": {
        "namespace": "User",
        "object": "writer-charlie",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-draft-3",
      "relation": "assigned_editor",
      "subject_set": {
        "namespace": "User",
        "object": "editor-diana",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-draft-3",
      "relation": "draft_editors",
      "subject_set": {
        "namespace": "User",
        "object": "writer-charlie",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-review-1",
      "relation": "author",
      "subject_set": {
        "namespace": "User",
        "object": "writer-alice",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-review-1",
      "relation": "assigned_editor",
      "subject_set": {
        "namespace": "User",
        "object": "editor-diana",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-review-1",
      "relation": "review_editors",
      "subject_set": {
        "namespace": "User",
        "object": "editor-diana",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-review-1",
      "relation": "review_publishers",
      "subject_set": {
        "namespace": "Role",
        "object": "publisher",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-review-2",
      "relation": "author",
      "subject_set": {
        "namespace": "User",
        "object": "writer-bob",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-review-2",
      "relation": "assigned_editor",
      "subject_set": {
        "namespace": "User",
        "object": "editor-eve",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-review-2",
      "relation": "review_editors",
      "subject_set": {
        "namespace": "User",
        "object": "editor-eve",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-review-2",
      "relation": "review_publishers",
      "subject_set": {
        "namespace": "Role",
        "object": "publisher",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-1",
      "relation": "author",
      "subject_set": {
        "namespace": "User",
        "object": "writer-alice",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-1",
      "relation": "assigned_editor",
      "subject_set": {
        "namespace": "User",
        "object": "editor-diana",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-1",
      "relation": "published_viewers",
      "subject_set": {
        "namespace": "Role",
        "object": "reader",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-1",
      "relation": "published_viewers",
      "subject_set": {
        "namespace": "Role",
        "object": "writer",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-1",
      "relation": "published_viewers",
      "subject_set": {
        "namespace": "Role",
        "object": "editor",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-1",
      "relation": "published_viewers",
      "subject_set": {
        "namespace": "Role",
        "object": "publisher",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-2",
      "relation": "author",
      "subject_set": {
        "namespace": "User",
        "object": "writer-charlie",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-2",
      "relation": "assigned_editor",
      "subject_set": {
        "namespace": "User",
        "object": "editor-eve",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-2",
      "relation": "published_viewers",
      "subject_set": {
        "namespace": "Role",
        "object": "reader",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-2",
      "relation": "published_viewers",
      "subject_set": {
        "namespace": "Role",
        "object": "writer",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-2",
      "relation": "published_viewers",
      "subject_set": {
        "namespace": "Role",
        "object": "editor",
        "relation": ""
      }
    },
    {
      "namespace": "Article",
      "object": "art-published-2",
      "relation": "published_viewers",
      "subject_set": {
        "namespace": "Role",
        "object": "publisher",
        "relation": ""
      }
    }
  ],
  "healthcare-records": [
    {
      "namespace": "Patient",
      "object": "patient-1",
      "relation": "care_team_doctors",
      "subject_set": {
        "namespace": "User",
        "object": "dr-smith",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-1",
      "relation": "care_team_doctors",
      "subject_set": {
        "namespace": "User",
        "object": "dr-jones",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-1",
      "relation": "care_team_nurses",
      "subject_set": {
        "namespace": "User",
        "object": "nurse-chen",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-1",
      "relation": "consented_viewers",
      "subject_set": {
        "namespace": "User",
        "object": "dr-specialist-lee",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-2",
      "relation": "care_team_doctors",
      "subject_set": {
        "namespace": "User",
        "object": "dr-jones",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-2",
      "relation": "care_team_nurses",
      "subject_set": {
        "namespace": "User",
        "object": "nurse-chen",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-2",
      "relation": "care_team_nurses",
      "subject_set": {
        "namespace": "User",
        "object": "nurse-patel",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-3",
      "relation": "care_team_doctors",
      "subject_set": {
        "namespace": "User",
        "object": "dr-garcia",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-3",
      "relation": "care_team_doctors",
      "subject_set": {
        "namespace": "User",
        "object": "dr-kim",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-3",
      "relation": "care_team_nurses",
      "subject_set": {
        "namespace": "User",
        "object": "nurse-wilson",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-3",
      "relation": "consented_viewers",
      "subject_set": {
        "namespace": "User",
        "object": "dr-specialist-lee",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-3",
      "relation": "consented_viewers",
      "subject_set": {
        "namespace": "User",
        "object": "therapist-brown",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-4",
      "relation": "care_team_doctors",
      "subject_set": {
        "namespace": "User",
        "object": "dr-kim",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-4",
      "relation": "care_team_nurses",
      "subject_set": {
        "namespace": "User",
        "object": "nurse-davis",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-5",
      "relation": "care_team_doctors",
      "subject_set": {
        "namespace": "User",
        "object": "dr-garcia",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-5",
      "relation": "care_team_nurses",
      "subject_set": {
        "namespace": "User",
        "object": "nurse-wilson",
        "relation": ""
      }
    },
    {
      "namespace": "Patient",
      "object": "patient-5",
      "relation": "care_team_nurses",
      "subject_set": {
        "namespace": "User",
        "object": "nurse-patel",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-1a",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-1",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-1b",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-1",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-1c",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-1",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-2a",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-2",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-2b",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-2",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-3a",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-3",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-3b",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-3",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-4a",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-4",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-4b",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-4",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-5a",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-5",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-5b",
      "relation": "patient",
      "subject_set": {
        "namespace": "Patient",
        "object": "patient-5",
        "relation": ""
      }
    },
    {
      "namespace": "MedicalRecord",
      "object": "record-1a",
      "relation": "emergency_access",
      "subject_set": {
        "namespace": "User",
        "object": "dr-garcia",
        "relation": ""
      }
    }
  ],
  "rag-document-access": [
    {
      "namespace": "Team",
      "object": "engineering",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "alice",
        "relation": ""
      }
    },
    {
      "namespace": "Team",
      "object": "engineering",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "bob",
        "relation": ""
      }
    },
    {
      "namespace": "Team",
      "object": "engineering",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "charlie",
        "relation": ""
      }
    },
    {
      "namespace": "Team",
      "object": "engineering",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "oscar",
        "relation": ""
      }
    },
    {
      "namespace": "Team",
      "object": "marketing",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "diana",
        "relation": ""
      }
    },
    {
      "namespace": "Team",
      "object": "marketing",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "eve",
        "relation": ""
      }
    },
    {
      "namespace": "Team",
      "object": "marketing",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "frank",
        "relation": ""
      }
    },
    {
      "namespace": "Team",
      "object": "design",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "grace",
        "relation": ""
      }
    },
    {
      "namespace": "Team",
      "object": "design",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "henry",
        "relation": ""
      }
    },
    {
      "namespace": "Team",
      "object": "leadership",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "irene",
        "relation": ""
      }
    },
    {
      "namespace": "Team",
      "object": "leadership",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "jack",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "api-design-doc",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "alice",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "api-design-doc",
      "relation": "editors",
      "subject_set": {
        "namespace": "User",
        "object": "bob",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "api-design-doc",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "engineering",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "deployment-runbook",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "bob",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "deployment-runbook",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "engineering",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "alice-private-notes",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "alice",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "brand-guidelines",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "diana",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "brand-guidelines",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "marketing",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "brand-guidelines",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "design",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "campaign-plan",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "eve",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "campaign-plan",
      "relation": "editors",
      "subject_set": {
        "namespace": "User",
        "object": "diana",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "campaign-plan",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "marketing",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "cross-team-roadmap",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "alice",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "cross-team-roadmap",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "engineering",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "cross-team-roadmap",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "marketing",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "cross-team-roadmap",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "design",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "cross-team-roadmap",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "leadership",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "shared-spec",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "bob",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "shared-spec",
      "relation": "editors",
      "subject_set": {
        "namespace": "User",
        "object": "diana",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "shared-spec",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "frank",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "eve-private-draft",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "eve",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "design-system-v2",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "grace",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "design-system-v2",
      "relation": "editors",
      "subject_set": {
        "namespace": "User",
        "object": "henry",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "design-system-v2",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "design",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "design-system-v2",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "engineering",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "ux-research-findings",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "henry",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "ux-research-findings",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "design",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "ux-research-findings",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "marketing",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "board-deck-q4",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "irene",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "board-deck-q4",
      "relation": "editors",
      "subject_set": {
        "namespace": "User",
        "object": "jack",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "board-deck-q4",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "leadership",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "org-restructure-plan",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "jack",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "budget-forecast",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "irene",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "budget-forecast",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "alice",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "budget-forecast",
      "relation": "viewers",
      "subject_set": {
        "namespace": "User",
        "object": "diana",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "product-launch-brief",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "diana",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "product-launch-brief",
      "relation": "editors",
      "subject_set": {
        "namespace": "User",
        "object": "grace",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "product-launch-brief",
      "relation": "editors",
      "subject_set": {
        "namespace": "User",
        "object": "alice",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "product-launch-brief",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "marketing",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "product-launch-brief",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "engineering",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "product-launch-brief",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "design",
        "relation": "members"
      }
    },
    {
      "namespace": "Document",
      "object": "incident-postmortem-42",
      "relation": "owner",
      "subject_set": {
        "namespace": "User",
        "object": "oscar",
        "relation": ""
      }
    },
    {
      "namespace": "Document",
      "object": "incident-postmortem-42",
      "relation": "viewers",
      "subject_set": {
        "namespace": "Team",
        "object": "engineering",
        "relation": "members"
      }
    }
  ],
  "rbac-app-access": [
    {
      "namespace": "Role",
      "object": "admin",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "alice",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "admin",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "bob",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "admin",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "greg",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "editor",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "charlie",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "editor",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "diana",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "editor",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "helen",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "editor",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "ivan",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "viewer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "eve",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "viewer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "frank",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "viewer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "judy",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "support",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "karen",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "support",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "leo",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "developer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "mike",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "developer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "nancy",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "developer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "oscar",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "billing-dashboard",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "admin",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "content-cms",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "admin",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "content-cms",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "editor",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "analytics-viewer",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "admin",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "analytics-viewer",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "editor",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "analytics-viewer",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "viewer",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "helpdesk-portal",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "admin",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "helpdesk-portal",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "support",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "ci-cd-pipeline",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "admin",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "ci-cd-pipeline",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "developer",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "staging-env",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "admin",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "staging-env",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "developer",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "staging-env",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "editor",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "internal-wiki",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "admin",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "internal-wiki",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "editor",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "internal-wiki",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "viewer",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "internal-wiki",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "support",
        "relation": ""
      }
    },
    {
      "namespace": "Application",
      "object": "internal-wiki",
      "relation": "allowed_roles",
      "subject_set": {
        "namespace": "Role",
        "object": "developer",
        "relation": ""
      }
    }
  ],
  "rbac-bank-accounts": [
    {
      "namespace": "Role",
      "object": "teller",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "sarah",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "teller",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "tom",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "teller",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "rachel",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "account_manager",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "maria",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "account_manager",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "james",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "account_manager",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "linda",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "branch_admin",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "patricia",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "branch_admin",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "robert",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "auditor",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "nancy",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "auditor",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "kevin",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "loan_officer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "diana",
        "relation": ""
      }
    },
    {
      "namespace": "Role",
      "object": "loan_officer",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "steve",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "checking-1001",
      "relation": "owners",
      "subject_set": {
        "namespace": "User",
        "object": "john-smith",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "checking-1001",
      "relation": "spouses",
      "subject_set": {
        "namespace": "User",
        "object": "jane-smith",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "checking-1001",
      "relation": "children",
      "subject_set": {
        "namespace": "User",
        "object": "timmy-smith",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "checking-1001",
      "relation": "children",
      "subject_set": {
        "namespace": "User",
        "object": "emma-smith",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "checking-1001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "teller",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "checking-1001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "account_manager",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "checking-1001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "auditor",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "checking-1001",
      "relation": "transferors_role",
      "subject_set": {
        "namespace": "Role",
        "object": "account_manager",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "checking-1001",
      "relation": "admins",
      "subject_set": {
        "namespace": "Role",
        "object": "branch_admin",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "savings-2001",
      "relation": "owners",
      "subject_set": {
        "namespace": "User",
        "object": "john-smith",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "savings-2001",
      "relation": "spouses",
      "subject_set": {
        "namespace": "User",
        "object": "jane-smith",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "savings-2001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "teller",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "savings-2001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "auditor",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "savings-2001",
      "relation": "transferors_role",
      "subject_set": {
        "namespace": "Role",
        "object": "account_manager",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "savings-2001",
      "relation": "admins",
      "subject_set": {
        "namespace": "Role",
        "object": "branch_admin",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "business-3001",
      "relation": "owners",
      "subject_set": {
        "namespace": "User",
        "object": "carlos-garcia",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "business-3001",
      "relation": "spouses",
      "subject_set": {
        "namespace": "User",
        "object": "maria-garcia",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "business-3001",
      "relation": "children",
      "subject_set": {
        "namespace": "User",
        "object": "luis-garcia",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "business-3001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "account_manager",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "business-3001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "auditor",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "business-3001",
      "relation": "transferors_role",
      "subject_set": {
        "namespace": "Role",
        "object": "account_manager",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "business-3001",
      "relation": "admins",
      "subject_set": {
        "namespace": "Role",
        "object": "branch_admin",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "vault-4001",
      "relation": "owners",
      "subject_set": {
        "namespace": "User",
        "object": "patricia-wong",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "vault-4001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "auditor",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "vault-4001",
      "relation": "admins",
      "subject_set": {
        "namespace": "Role",
        "object": "branch_admin",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "mortgage-5001",
      "relation": "owners",
      "subject_set": {
        "namespace": "User",
        "object": "john-smith",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "mortgage-5001",
      "relation": "spouses",
      "subject_set": {
        "namespace": "User",
        "object": "jane-smith",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "mortgage-5001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "loan_officer",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "mortgage-5001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "auditor",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "mortgage-5001",
      "relation": "transferors_role",
      "subject_set": {
        "namespace": "Role",
        "object": "loan_officer",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "mortgage-5001",
      "relation": "admins",
      "subject_set": {
        "namespace": "Role",
        "object": "branch_admin",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "credit-line-6001",
      "relation": "owners",
      "subject_set": {
        "namespace": "User",
        "object": "carlos-garcia",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "credit-line-6001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "loan_officer",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "credit-line-6001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "account_manager",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "credit-line-6001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "auditor",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "credit-line-6001",
      "relation": "transferors_role",
      "subject_set": {
        "namespace": "Role",
        "object": "loan_officer",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "credit-line-6001",
      "relation": "admins",
      "subject_set": {
        "namespace": "Role",
        "object": "branch_admin",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "trust-7001",
      "relation": "owners",
      "subject_set": {
        "namespace": "User",
        "object": "patricia-wong",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "trust-7001",
      "relation": "spouses",
      "subject_set": {
        "namespace": "User",
        "object": "david-wong",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "trust-7001",
      "relation": "children",
      "subject_set": {
        "namespace": "User",
        "object": "lily-wong",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "trust-7001",
      "relation": "children",
      "subject_set": {
        "namespace": "User",
        "object": "max-wong",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "trust-7001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "auditor",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "trust-7001",
      "relation": "admins",
      "subject_set": {
        "namespace": "Role",
        "object": "branch_admin",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "escrow-8001",
      "relation": "owners",
      "subject_set": {
        "namespace": "User",
        "object": "carlos-garcia",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "escrow-8001",
      "relation": "spouses",
      "subject_set": {
        "namespace": "User",
        "object": "maria-garcia",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "escrow-8001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "account_manager",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "escrow-8001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "auditor",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "escrow-8001",
      "relation": "transferors_role",
      "subject_set": {
        "namespace": "Role",
        "object": "account_manager",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "escrow-8001",
      "relation": "admins",
      "subject_set": {
        "namespace": "Role",
        "object": "branch_admin",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "college-fund-9001",
      "relation": "owners",
      "subject_set": {
        "namespace": "User",
        "object": "john-smith",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "college-fund-9001",
      "relation": "children",
      "subject_set": {
        "namespace": "User",
        "object": "timmy-smith",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "college-fund-9001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "auditor",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "college-fund-9001",
      "relation": "admins",
      "subject_set": {
        "namespace": "Role",
        "object": "branch_admin",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "joint-savings-10001",
      "relation": "owners",
      "subject_set": {
        "namespace": "User",
        "object": "patricia-wong",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "joint-savings-10001",
      "relation": "spouses",
      "subject_set": {
        "namespace": "User",
        "object": "david-wong",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "joint-savings-10001",
      "relation": "children",
      "subject_set": {
        "namespace": "User",
        "object": "lily-wong",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "joint-savings-10001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "teller",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "joint-savings-10001",
      "relation": "viewers_role",
      "subject_set": {
        "namespace": "Role",
        "object": "auditor",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "joint-savings-10001",
      "relation": "transferors_role",
      "subject_set": {
        "namespace": "Role",
        "object": "account_manager",
        "relation": ""
      }
    },
    {
      "namespace": "BankAccount",
      "object": "joint-savings-10001",
      "relation": "admins",
      "subject_set": {
        "namespace": "Role",
        "object": "branch_admin",
        "relation": ""
      }
    }
  ],
  "saas-feature-gating": [
    {
      "namespace": "Organization",
      "object": "startup-co",
      "relation": "admins",
      "subject_set": {
        "namespace": "User",
        "object": "alice",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "startup-co",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "bob",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "startup-co",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "charlie",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "growth-co",
      "relation": "admins",
      "subject_set": {
        "namespace": "User",
        "object": "diana",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "growth-co",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "eve",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "growth-co",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "frank",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "growth-co",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "grace",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "megacorp",
      "relation": "admins",
      "subject_set": {
        "namespace": "User",
        "object": "henry",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "megacorp",
      "relation": "admins",
      "subject_set": {
        "namespace": "User",
        "object": "irene",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "megacorp",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "jack",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "megacorp",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "karen",
        "relation": ""
      }
    },
    {
      "namespace": "Organization",
      "object": "megacorp",
      "relation": "members",
      "subject_set": {
        "namespace": "User",
        "object": "leo",
        "relation": ""
      }
    },
    {
      "namespace": "Plan",
      "object": "free",
      "relation": "org_members",
      "subject_set": {
        "namespace": "Organization",
        "object": "startup-co",
        "relation": "members"
      }
    },
    {
      "namespace": "Plan",
      "object": "free",
      "relation": "org_members",
      "subject_set": {
        "namespace": "Organization",
        "object": "startup-co",
        "relation": "admins"
      }
    },
    {
      "namespace": "Plan",
      "object": "pro",
      "relation": "org_members",
      "subject_set": {
        "namespace": "Organization",
        "object": "growth-co",
        "relation": "members"
      }
    },
    {
      "namespace": "Plan",
      "object": "pro",
      "relation": "org_members",
      "subject_set": {
        "namespace": "Organization",
        "object": "growth-co",
        "relation": "admins"
      }
    },
    {
      "namespace": "Plan",
      "object": "enterprise",
      "relation": "org_members",
      "subject_set": {
        "namespace": "Organization",
        "object": "megacorp",
        "relation": "members"
      }
    },
    {
      "namespace": "Plan",
      "object": "enterprise",
      "relation": "org_members",
      "subject_set": {
        "namespace": "Organization",
        "object": "megacorp",
        "relation": "admins"
      }
    },
    {
      "namespace": "Feature",
      "object": "basic-dashboard",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "free",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "api-access",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "free",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "export-csv",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "free",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "custom-branding",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "pro",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "sso",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "pro",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "audit-log",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "pro",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "basic-dashboard",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "pro",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "api-access",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "pro",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "export-csv",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "pro",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "advanced-analytics",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "enterprise",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "priority-support",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "enterprise",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "dedicated-infra",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "enterprise",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "basic-dashboard",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "enterprise",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "api-access",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "enterprise",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "export-csv",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "enterprise",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "custom-branding",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "enterprise",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "sso",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "enterprise",
        "relation": ""
      }
    },
    {
      "namespace": "Feature",
      "object": "audit-log",
      "relation": "included_in",
      "subject_set": {
        "namespace": "Plan",
        "object": "enterprise",
        "relation": ""
      }
    }
  ]
};

export default OFFLINE_EXAMPLES;
